### ISSUE TITLE
Having trouble getting it to run

### ISSUE THREAD

**Issue by leptoid** [seiya-dev/funimation-downloader-nx#1]
When I try to run, I get this fun stuff! :D 
```
=== Funimation Downloader NX 2.2.0 ===

module.js:472
    throw err;
    ^

Error: Cannot find module 'sei-helper'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\ripped\funimation-downloader-nx-master\scripts\funidl.js:14:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
Any ideas what that's all about?  This happens when running "funi.bat" with any option.  I am positive that I think I have all the dependencies installed.

**Comment by leptoid** [comment]
self troubleshooting step #1.  
'sei-helper' can be optained by typing the following at command prompt:
`
npm i sei-helper
 `

**Comment by leptoid** [comment]
Ok, to get the NPM required dependencies, you need to type the following at the command prompt:
`
npm i sei-helper
npm i yargs
npm i request
`
This should get rid of all errors (that I have encountered so far).

**Comment by leptoid** [comment]
New stuff:
Can list older items such as Trigun episodes by typing the following:
```
funi --search Trigun
funi -s 31635
```
If you do the show Freezing, it errors... kind of.
```
funi --search Freezing
funi -s 36098
```
This brings an error right as it gets to the ovas/season 2 shows.
```
[s01e12 episode] Freezing - #12 Satellizer vs. Pandora (23:51) [HD1080, English, Japanese]
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: write EIO
    at exports._errnoException (util.js:1034:11)
    at WriteStream.Socket._writeGeneric (net.js:723:26)
    at WriteStream.Socket._write (net.js:742:8)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at WriteStream.Writable.write (_stream_writable.js:241:11)
    at WriteStream.Socket.write (net.js:669:40)
    at Console.log (console.js:43:16)
    at parseEpsData (D:\Torrents\ripped\funimation-downloader-nx-master\scripts\funidl.js:302:11)
    at Request.request.get [as _callback] (D:\Torrents\ripped\funimation-downloader-nx-master\scripts\funidl.js:272:4)
Press any key to continue . . .
```
However, if you type:
`
funi -s 36098 >info.txt
`
This nicely pipes out the information correctly.  I have yet to get it to download anything though.  If you have ideas, please let me know.

**Comment by seiya-git** [comment]
Try to remove  `@chcp 65001>nul` line from funi.bat

**Comment by leptoid** [comment]
That worked.  Thanks.
Now I am just working on figuring out the syntax for selecting a specific episode, such as "s01e12" or whatever I need to input... and correct whatever I did to the dependencies. :D

Thanks for the assistance!

**Comment by albogango** [comment]
@leptoid @seiya-git Could I perhaps get a layman's explanation in how to fix this issue? I've extracted the folder and get the above message when I open "funi.bat".

**Comment by leptoid** [comment]
Hi.  Basically you are just removing some text from "funi.bat".  You can do this by right clicking the file and picking "edit" from the dropdown box, and then making sure the file only says the following inside of it:
```
@echo off
"node" "%~dp0.\scripts\funidl.js" %*
pause
```
It would be easier to edit (as in look better) if you use Notepad++ to edit it.  That can be downloaded from here:  [](https://notepad-plus-plus.org/download)

**Comment by albogango** [comment]
I did exactly that and am still receiving the same message. I don't think I installed MKVToolNix and MP4Box properly. Is there a prerequisite to installing these?

**Comment by seiya-git** [comment]
Fixed with latest commit 3d83230.

**Comment by CrazySD93** [comment]
At this part of getting it to work
> npm i sei-helper
> npm i yargs
> npm i request

Whenever I try one of those, it always throws this up, and even from searching elsewhere, I can't get it to work, any advice?

C:\Users\XXXXX>npm i sei-helper
npm WARN onload-script   code: 'MODULE_NOT_FOUND' }
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\XXXXX\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\XXXXX\package.json'
npm WARN XXXXX No description
npm WARN XXXXXNo repository field.
npm WARN XXXXXNo README data
npm WARN XXXXXNo license field.

+ sei-helper@1.2.0
updated 1 package in 1.434s

It says updated but when I run the funi.bat again, it says the dependency is still missing.

**Comment by leptoid** [comment]
I may be reaching here, but if you ran a command prompt and did not transition to the folder you extracted the "funimation-downloader-nx" script to, you aren't going to get your stuff to work.

Realistically, it has to be at "./funimation-downloader-nx/scripts/"        <----sorry for / formatting.  been using Linux

in Windows the easiest way to get the command prompt in the proper location is to open Windows Explorer, browse to the "funimation-downloader-nx" folder, hold down left shift, right click scripts folder, click the browse the dropdown menu for "Open Command Prompt here"
at the command prompt type:
`npm i`
a bunch of umm... stuff should happen.
type:
```
cd ..
funi --search dbz
```

But yeah, it isn't working because you aren't in the scripts folder.

**Comment by Vigilence** [comment]
I've followed everything listed here and in the bin thread and everything seems to be working fine.  However, when the download finishes the .ts file doesn't auto mux into an .mp4 container.  

mp4box is in the bin folder and listed correctly in the config file so I am at a loss.

const binDir = __dirname+'/../../bin'

module.exports = {
	mkvmerge:   binDir+'/mkvtoolnix/mkvmerge.exe',
	mp4box:     binDir+'/mp4box/mp4box.exe',
	streamlink: binDir+'/streamlink/bin/streamlink.exe',
	tsmuxer:    binDir+'/tsMuxeR/tsMuxeR.exe'
};

**Comment by CrazySD93** [comment]
Launching from powershell, Windows 10.

```
PS F:\funimation-downloader-nx-master> ./funi -s 369617 --sel S001

=== Funimation Downloader NX 2.5.0 ===

[#369617] Seven Mortal Sins (2017)
[0001] Seven Mortal Sins - #01 The Proud Fallen Angel (23:36) [HD1080, English]
[0002] Seven Mortal Sins - #02 Driven Wild by Envy (23:36) [HD1080, English]
[0003] Seven Mortal Sins - #03 Beach of Lust (23:36) [HD1080, English]
[0004] Seven Mortal Sins - #04 The Town of Fog Where Greed Brews (23:36) [HD1080, English]
[S001] Seven Mortal Sins - #04.5 This is Indeed the Work of Demons… (23:36) [HD1080, English] (selected)
[0005] Seven Mortal Sins - #05 The Languid Diva (23:36) [HD1080, English]
[0006] Seven Mortal Sins - #06 Sloth Online (23:36) [HD1080, English]
[0007] Seven Mortal Sins - #07 Guiltless Gluttony (23:36) [HD1080, English]
[0008] Seven Mortal Sins - #08 Unleashed Wrath (23:36) [HD1080, English]
[0009] Seven Mortal Sins - #09 Ye Abandon All Hope (23:36) [HD1080, English]
[0010] Seven Mortal Sins - #10 Love Your Enemies and Pray for Those Who Persecute You (23:36) [HD1080, English]
[0011] Seven Mortal Sins - #11 Ask, and It Shall Be Given to You (23:36) [HD1080, English]
[0012] Seven Mortal Sins - #12 God's In His Heaven, All's Right With the World (23:36) [HD1080, English]

[INFO] Output filename: [Funimation] Seven Mortal Sins - 04.5 [1080p]

[INFO] Available audio tracks:
[#384021] English (selected)
Error:
Status: 404
    at Request.request [as _callback] (F:\funimation-downloader-nx-master\scripts\funidl.js:459:19)
    at Request.self.callback (F:\funimation-downloader-nx-master\scripts\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (F:\funimation-downloader-nx-master\scripts\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (F:\funimation-downloader-nx-master\scripts\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20) '\n'
Press any key to continue . . .
```

I also can't seem to figure out how to properly set Boolean switches to have an affect in funidl.js .boolean('h'), though I can set fine in funi.bat.

**Comment by leptoid** [comment]
You might get better responses if you start your own issues thread... that said, here we go:
@CrazySD93 - your will fail because there is a decimal in the filename.  To correct it, manually name the file using the "-t" option.

`funi -s 369617 --sel S001 -t "Seven Mortal Sins - 01"`

**Comment by leptoid** [comment]
@Vigilence, using the code you posted, funimation-downloader-nx doesn't even work.
`-q 0 `  This option requires a valid input.  I am going to replace the "0" with "270p" though you can use 480p, 720p, or 1080p.

The problem you have is due to you using the BETA version of this script.  That version does not download audio yet, therefore there is nothing to mux.  You have to use the master copy of the script to have it functioning correctly.  Beta is... well, Beta aka still in development.
This is the link for the master:
[https://github.com/seiya-dev/funimation-downloader-nx](url)
Replace your copy with this and see if it works.
