### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by nolan1989** [seiya-dev/funimation-downloader-nx#10]
I'm receiving the following error when running the Funi.Bat. I've tried the solutions listed in the other issue reports about the problem, but no luck as of yet. I am running windows 10, if that matters. Error message is:

C:\Funimation DL\scripts\funidl.js:131
async function auth(){
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
Press any key to continue . . .

**Comment by clienthax** [comment]
You need to use the latest nodejs, not the recommended one :)

**Comment by seiya-git** [comment]
#6
