### ISSUE TITLE
Seems broken from now on

### ISSUE THREAD

**Issue by Golumpa** [seiya-dev/funimation-downloader-nx#11]
Was working yesterday but not anymore, they must have patched it or something.

> [INFO] Available audio tracks:
[#512087] English (selected)
Error:
Status: 404
    at Request.request [as _callback] (/root/funi/scripts/funidl.js:450:19)
    at Request.self.callback (/root/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/root/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/root/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20) '\n'

**Comment by seiya-git** [comment]
Can you give me show id and episode id?

**Comment by Golumpa** [comment]
Show ID: #155585
Episode ID: #512087

It should download:
Monster Hunter Stories Ride On - #43

**Comment by Golumpa** [comment]
Im not great with reverse enginering but I have a feeling they changed the API a bit for getting the signed URL (line 293)

**Comment by seiya-git** [comment]
Strange. They don't change url for app and site use funtimation domain (region specific) for getting streams.

**Comment by seiya-git** [comment]
Fixed with latest [release](https://github.com/seiya-dev/funimation-downloader-nx/releases/tag/2.4.1).
