### ISSUE TITLE
Having trouble getting it to run

### ISSUE THREAD

**Issue by CrazySD93** [seiya-dev/funimation-downloader-nx#19]
Running in windows Powershell, always get an Error: Status: 404

```
PS F:\funimation-downloader-nx-master> ./funi -s 369617 --sel 0001

=== Funimation Downloader NX 2.5.0 ===

[#369617] Seven Mortal Sins (2017)
[0001] Seven Mortal Sins - #01 The Proud Fallen Angel (23:36) [HD1080, English] (selected)
[0002] Seven Mortal Sins - #02 Driven Wild by Envy (23:36) [HD1080, English]
[0003] Seven Mortal Sins - #03 Beach of Lust (23:36) [HD1080, English]
[0004] Seven Mortal Sins - #04 The Town of Fog Where Greed Brews (23:36) [HD1080, English]
[S001] Seven Mortal Sins - #04.5 This is Indeed the Work of Demons… (23:36) [HD1080, English]
[0005] Seven Mortal Sins - #05 The Languid Diva (23:36) [HD1080, English]
[0006] Seven Mortal Sins - #06 Sloth Online (23:36) [HD1080, English]
[0007] Seven Mortal Sins - #07 Guiltless Gluttony (23:36) [HD1080, English]
[0008] Seven Mortal Sins - #08 Unleashed Wrath (23:36) [HD1080, English]
[0009] Seven Mortal Sins - #09 Ye Abandon All Hope (23:36) [HD1080, English]
[0010] Seven Mortal Sins - #10 Love Your Enemies and Pray for Those Who Persecute You (23:36) [HD1080, English]
[0011] Seven Mortal Sins - #11 Ask, and It Shall Be Given to You (23:36) [HD1080, English]
[0012] Seven Mortal Sins - #12 God's In His Heaven, All's Right With the World (23:36) [HD1080, English]

[INFO] Output filename: [Funimation] Seven Mortal Sins - 01 [1080p]

[INFO] Available audio tracks:
[#369674] English (selected)
Error:
Status: 404
    at Request.request [as _callback] (F:\funimation-downloader-nx-master\scripts\funidl.js:459:19)
    at Request.self.callback (F:\funimation-downloader-nx-master\scripts\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (F:\funimation-downloader-nx-master\scripts\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (F:\funimation-downloader-nx-master\scripts\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20) '\n'
Press any key to continue . . .
```

**Comment by seiya-git** [comment]
Do you try latest version?
