### ISSUE TITLE
Error: Command failed:

### ISSUE THREAD

**Issue by leptoid** [seiya-dev/funimation-downloader-nx#2]
Hello again.  I still have not successfully gotten this to work.  I am close, just having issues debugging.  This is where I am:
The following works...
```
D:\funimation-downloader-nx-master>**funi --search "Tokyo Ghoul"**

=== Funimation Downloader NX 2.2.5 ===

**[#37172] Tokyo Ghoul (2014)**
Total titles found: 1

Press any key to continue . . .
```
This works fine and gives me episode numbers (1, 2, 3...)
```
D:\funimation-downloader-nx-master>funi -s 37172

=== Funimation Downloader NX 2.2.5 ===

[s01e01 episode] Tokyo Ghoul - #1 Tragedy (26:08) [HD1080, English, Japanese]
[s01e02 episode] Tokyo Ghoul - #2 Incubation (24:06) [HD1080, Japanese, English]
[s01e03 episode] Tokyo Ghoul - #3 Dove (24:06) [HD1080, English, Japanese]
[s01e04 episode] Tokyo Ghoul - #4 Supper (24:06) [HD1080, English, Japanese]
[s01e05 episode] Tokyo Ghoul - #5 Scars (24:11) [HD1080, English, Japanese]
[s01e06 episode] Tokyo Ghoul - #6 Cloudburst (24:06) [HD1080, Japanese, English]
[s01e07 episode] Tokyo Ghoul - #7 Captivity (24:12) [HD1080, English, Japanese]
[s01e08 episode] Tokyo Ghoul - #8 Circular (24:11) [HD1080, English, Japanese]
[s01e09 episode] Tokyo Ghoul - #9 Birdcage (24:11) [HD1080, English, Japanese]
[s01e10 episode] Tokyo Ghoul - #10 Aogiri (24:11) [HD1080, English, Japanese]
[s01e11 episode] Tokyo Ghoul - #11 High Spirits (24:11) [HD1080, English, Japanese]
[s01e12 episode] Tokyo Ghoul - #12 Ghoul (24:11) [HD1080, English, Japanese]
[s02e13 episode] Tokyo Ghoul S2 - #13 √A - New Surge (24:11) [HD1080, English, Japanese]
[s02e14 episode] Tokyo Ghoul S2 - #14 √A - Dancing Flowers (24:10) [HD1080, English, Japanese]
[s02e15 episode] Tokyo Ghoul S2 - #15 √A - Hangman (24:14) [HD1080, English, Japanese]
[s02e16 episode] Tokyo Ghoul S2 - #16 √A - Deeper Layers (24:10) [HD1080, English, Japanese]
[s02e17 episode] Tokyo Ghoul S2 - #17 √A - Rift (24:10) [HD1080, English, Japanese]
[s02e18 episode] Tokyo Ghoul S2 - #18 √A - Thousand Paths (24:11) [HD1080, English, Japanese]
[s02e19 episode] Tokyo Ghoul S2 - #19 √A - Permeation (24:11) [HD1080, English, Japanese]
[s02e20 episode] Tokyo Ghoul S2 - #20 √A - Old Nines (24:11) [HD1080, English, Japanese]
[s02e21 episode] Tokyo Ghoul S2 - #21 √A - City In Waiting (24:11) [HD1080, English, Japanese]
[s02e22 episode] Tokyo Ghoul S2 - #22 √A - Last Rain (24:11) [HD1080, English, Japanese]
[s02e23 episode] Tokyo Ghoul S2 - #23 √A - Deluge of Flowers (24:09) [HD1080, English, Japanese]
[s02e24 episode] Tokyo Ghoul S2 - #24 √A - Ken (24:11) [HD1080, English, Japanese]

Press any key to continue . . .
```
This is where the code fails.
```
D:\funimation-downloader-nx-master>funi -s 37172 --sel 1

=== Funimation Downloader NX 2.2.5 ===

[s01e01 episode] Tokyo Ghoul - #1 Tragedy (26:08) [HD1080, English, Japanese] (selected)
[s01e02 episode] Tokyo Ghoul - #2 Incubation (24:06) [HD1080, Japanese, English]
[s01e03 episode] Tokyo Ghoul - #3 Dove (24:06) [HD1080, English, Japanese]
[s01e04 episode] Tokyo Ghoul - #4 Supper (24:06) [HD1080, English, Japanese]
[s01e05 episode] Tokyo Ghoul - #5 Scars (24:11) [HD1080, English, Japanese]
[s01e06 episode] Tokyo Ghoul - #6 Cloudburst (24:06) [HD1080, Japanese, English]
[s01e07 episode] Tokyo Ghoul - #7 Captivity (24:12) [HD1080, English, Japanese]
[s01e08 episode] Tokyo Ghoul - #8 Circular (24:11) [HD1080, English, Japanese]
[s01e09 episode] Tokyo Ghoul - #9 Birdcage (24:11) [HD1080, English, Japanese]
[s01e10 episode] Tokyo Ghoul - #10 Aogiri (24:11) [HD1080, English, Japanese]
[s01e11 episode] Tokyo Ghoul - #11 High Spirits (24:11) [HD1080, English, Japanese]
[s01e12 episode] Tokyo Ghoul - #12 Ghoul (24:11) [HD1080, English, Japanese]
[s02e13 episode] Tokyo Ghoul S2 - #13 √A - New Surge (24:11) [HD1080, English, Japanese]
[s02e14 episode] Tokyo Ghoul S2 - #14 √A - Dancing Flowers (24:10) [HD1080, English, Japanese]
[s02e15 episode] Tokyo Ghoul S2 - #15 √A - Hangman (24:14) [HD1080, English, Japanese]
[s02e16 episode] Tokyo Ghoul S2 - #16 √A - Deeper Layers (24:10) [HD1080, English, Japanese]
[s02e17 episode] Tokyo Ghoul S2 - #17 √A - Rift (24:10) [HD1080, English, Japanese]
[s02e18 episode] Tokyo Ghoul S2 - #18 √A - Thousand Paths (24:11) [HD1080, English, Japanese]
[s02e19 episode] Tokyo Ghoul S2 - #19 √A - Permeation (24:11) [HD1080, English, Japanese]
[s02e20 episode] Tokyo Ghoul S2 - #20 √A - Old Nines (24:11) [HD1080, English, Japanese]
[s02e21 episode] Tokyo Ghoul S2 - #21 √A - City In Waiting (24:11) [HD1080, English, Japanese]
[s02e22 episode] Tokyo Ghoul S2 - #22 √A - Last Rain (24:11) [HD1080, English, Japanese]
[s02e23 episode] Tokyo Ghoul S2 - #23 √A - Deluge of Flowers (24:09) [HD1080, English, Japanese]
[s02e24 episode] Tokyo Ghoul S2 - #24 √A - Ken (24:11) [HD1080, English, Japanese]
Output filename: [Funimation] Tokyo Ghoul - 01 [720p]

Available audio tracks:
[#96310] English (selected)
[#95024] Japanese

> "streamlink" "hlsvariant://https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1351385/English/1351385_English_a3aae8fe-2854-e611-80c5-0017a4776c06.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMTMyZnVtaTZkaTF3YS5jbG91ZGZyb250Lm5ldC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDkzMzU0MTk2fX19XX0_&Signature=LjN6ni0ywv6AK8pByYkCpmNopPkvFUiaw0h4XOfTpuyDFhw32NU-vaFCuBWM9Je1NF606imDziAsD6q7p1zQdcf~zT1LzU7OdhX-Fyy08xNGkBu5PZi4YjSjRtKzbOJT1zLZ1QPPpYdfT5hZXFsqctNZCUS7ltajt0MXqeZjLsIoVLMYMU-lpPmEH8TR~T80WpkFRwZFe5p2PSWtSXtXw0aCqzBxf5amA3SrHoLQxGiREA8tKFr-mZhpfFKh1CTwQEVXZApVos4IegLFcvOX3BWhQHKzO6sUxG8IsbqoxjmJZaFuWUkn0aj9jbC9zC3PismYfQ7rmoj13-YH8jeQ~Q__&Key-Pair-Id=APKAIHNXECY27H4O6NIA" 720p --hls-segment-attempts 10 --hls-segment-threads 10 --hls-segment-timeout 60 -o "[Funimation] Tokyo Ghoul - 01 [720p].ts"

'"D:\funimation-downloader-nx-master\bin\streamlink\build\streamlink"' is not recognized as an internal or external command,operable program or batch file.child_process.js:524
    throw err;
    ^

Error: Command failed: "D:\funimation-downloader-nx-master\bin\streamlink\build\streamlink" "hlsvariant://https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1351385/English/1351385_English_a3aae8fe-2854-e611-80c5-0017a4776c06.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMTMyZnVtaTZkaTF3YS5jbG91ZGZyb250Lm5ldC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDkzMzU0MTk2fX19XX0_&Signature=LjN6ni0ywv6AK8pByYkCpmNopPkvFUiaw0h4XOfTpuyDFhw32NU-vaFCuBWM9Je1NF606imDziAsD6q7p1zQdcf~zT1LzU7OdhX-Fyy08xNGkBu5PZi4YjSjRtKzbOJT1zLZ1QPPpYdfT5hZXFsqctNZCUS7ltajt0MXqeZjLsIoVLMYMU-lpPmEH8TR~T80WpkFRwZFe5p2PSWtSXtXw0aCqzBxf5amA3SrHoLQxGiREA8tKFr-mZhpfFKh1CTwQEVXZApVos4IegLFcvOX3BWhQHKzO6sUxG8IsbqoxjmJZaFuWUkn0aj9jbC9zC3PismYfQ7rmoj13-YH8jeQ~Q__&Key-Pair-Id=APKAIHNXECY27H4O6NIA" 720p --hls-segment-attempts 10 --hls-segment-threads 10 --hls-segment-timeout 60 -o "[Funimation] Tokyo Ghoul - 01 [720p].ts"
    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at Object.exec (D:\funimation-downloader-nx-master\scripts\node_modules\sei-helper\sei-helper.js:126:28)
    at downloadStream (D:\funimation-downloader-nx-master\scripts\funidl.js:433:7)
    at parseStream (D:\funimation-downloader-nx-master\scripts\funidl.js:420:4)
    at Request.request.get [as _callback] (D:\funimation-downloader-nx-master\scripts\funidl.js:402:4)
    at Request.self.callback (D:\funimation-downloader-nx-master\scripts\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (D:\funimation-downloader-nx-master\scripts\node_modules\request\request.js:1171:10)

Press any key to continue . . .
```
So then... I decided "Maybe streamlink is bad.  Nope.  Not that.  how do I know?  Well, I moved on to updating "npm" which I learned all about on [https://github.com/felixrieseberg/npm-windows-upgrade](https://github.com/felixrieseberg/npm-windows-upgrade).
To make it simple, ran PowerShell as admin.  Found out I'm not allowing scripts... probably, so I enabled that with this:
`
Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
`
I then ran the following 2 commands in PowerShell:
```
npm install --global --production npm-windows-upgrade
npm-windows-upgrade
```
This made a whole lot of fun.  Chose the newest version which is 4.6.1.
Tried **funi.bat** in PowerShell as a test.  It did something different.
```
PS D:\funimation-downloader-nx-master> .\funi.bat  --search "Tokyo Ghoul"

=== Funimation Downloader NX 2.2.0 ===

[#37172] Tokyo Ghoul (2014)
Total titles found: 1

Press any key to continue . . .
```
```
PS D:\funimation-downloader-nx-master> .\funi.bat  -s 37172 --sel 1

=== Funimation Downloader NX 2.2.0 ===

[s01e01 episode] Tokyo Ghoul - #1 Tragedy (26:08) [HD1080, English, Japanese] (selected)
[s01e02 episode] Tokyo Ghoul - #2 Incubation (24:06) [HD1080, Japanese, English]
[s01e03 episode] Tokyo Ghoul - #3 Dove (24:06) [HD1080, English, Japanese]
[s01e04 episode] Tokyo Ghoul - #4 Supper (24:06) [HD1080, English, Japanese]
[s01e05 episode] Tokyo Ghoul - #5 Scars (24:11) [HD1080, English, Japanese]
[s01e06 episode] Tokyo Ghoul - #6 Cloudburst (24:06) [HD1080, Japanese, English]
[s01e07 episode] Tokyo Ghoul - #7 Captivity (24:12) [HD1080, English, Japanese]
[s01e08 episode] Tokyo Ghoul - #8 Circular (24:11) [HD1080, English, Japanese]
[s01e09 episode] Tokyo Ghoul - #9 Birdcage (24:11) [HD1080, English, Japanese]
[s01e10 episode] Tokyo Ghoul - #10 Aogiri (24:11) [HD1080, English, Japanese]
[s01e11 episode] Tokyo Ghoul - #11 High Spirits (24:11) [HD1080, English, Japanese]
[s01e12 episode] Tokyo Ghoul - #12 Ghoul (24:11) [HD1080, English, Japanese]
[s02e13 episode] Tokyo Ghoul S2 - #13 √A - New Surge (24:11) [HD1080, English, Japanese]
[s02e14 episode] Tokyo Ghoul S2 - #14 √A - Dancing Flowers (24:10) [HD1080, English, Japanese]
[s02e15 episode] Tokyo Ghoul S2 - #15 √A - Hangman (24:14) [HD1080, English, Japanese]
[s02e16 episode] Tokyo Ghoul S2 - #16 √A - Deeper Layers (24:10) [HD1080, English, Japanese]
[s02e17 episode] Tokyo Ghoul S2 - #17 √A - Rift (24:10) [HD1080, English, Japanese]
[s02e18 episode] Tokyo Ghoul S2 - #18 √A - Thousand Paths (24:11) [HD1080, English, Japanese]
[s02e19 episode] Tokyo Ghoul S2 - #19 √A - Permeation (24:11) [HD1080, English, Japanese]
[s02e20 episode] Tokyo Ghoul S2 - #20 √A - Old Nines (24:11) [HD1080, English, Japanese]
[s02e21 episode] Tokyo Ghoul S2 - #21 √A - City In Waiting (24:11) [HD1080, English, Japanese]
[s02e22 episode] Tokyo Ghoul S2 - #22 √A - Last Rain (24:11) [HD1080, English, Japanese]
[s02e23 episode] Tokyo Ghoul S2 - #23 √A - Deluge of Flowers (24:09) [HD1080, English, Japanese]
[s02e24 episode] Tokyo Ghoul S2 - #24 √A - Ken (24:11) [HD1080, English, Japanese]
Output filename: [Funimation] Tokyo Ghoul - 01 [720p]

Available audio tracks:
[#96310] English (selected)
[#95024] Japanese

**Error (4): no valid Free Avails for this experience**

Press any key to continue . . .
PS D:\funimation-downloader-nx-master>
```
"Error (4): no valid Free Avails for this experience"  <--- No idea what this is about.

So yep... still can't get it to work. :(

**Comment by seiya-git** [comment]
Check path to streamlink executable, for windows this is must be: ```".\bin\streamlink\build\streamlink.exe"``` not ```".\bin\streamlink\build\streamlink\streamlink.exe"```

```Error (4): no valid Free Avails for this experience``` means video only for premium account

**Comment by leptoid** [comment]
ooooh..... 
Fixed free avails by authenticating each time I see that thanks to your explanation.
Fixed streamlink location.  After moving Streamlink EXE to Builds folder (Shifting it all up a directory...) I get this:
```
D:\funimation-downloader-nx-master>funi -s 37172 --sel 1

=== Funimation Downloader NX 2.2.5 ===

[s01e01 episode] Tokyo Ghoul - #1 Tragedy (26:08) [HD1080, English, Japanese] (selected)
[s01e02 episode] Tokyo Ghoul - #2 Incubation (24:06) [HD1080, Japanese, English]
[s01e03 episode] Tokyo Ghoul - #3 Dove (24:06) [HD1080, English, Japanese]
[s01e04 episode] Tokyo Ghoul - #4 Supper (24:06) [HD1080, English, Japanese]
[s01e05 episode] Tokyo Ghoul - #5 Scars (24:11) [HD1080, English, Japanese]
[s01e06 episode] Tokyo Ghoul - #6 Cloudburst (24:06) [HD1080, Japanese, English]
[s01e07 episode] Tokyo Ghoul - #7 Captivity (24:12) [HD1080, English, Japanese]
[s01e08 episode] Tokyo Ghoul - #8 Circular (24:11) [HD1080, English, Japanese]
[s01e09 episode] Tokyo Ghoul - #9 Birdcage (24:11) [HD1080, English, Japanese]
[s01e10 episode] Tokyo Ghoul - #10 Aogiri (24:11) [HD1080, English, Japanese]
[s01e11 episode] Tokyo Ghoul - #11 High Spirits (24:11) [HD1080, English, Japanese]
[s01e12 episode] Tokyo Ghoul - #12 Ghoul (24:11) [HD1080, English, Japanese]
[s02e13 episode] Tokyo Ghoul S2 - #13 ûA - New Surge (24:11) [HD1080, English, Japanese]
[s02e14 episode] Tokyo Ghoul S2 - #14 ûA - Dancing Flowers (24:10) [HD1080, English, Japanese]
[s02e15 episode] Tokyo Ghoul S2 - #15 ûA - Hangman (24:14) [HD1080, English, Japanese]
[s02e16 episode] Tokyo Ghoul S2 - #16 ûA - Deeper Layers (24:10) [HD1080, English, Japanese]
[s02e17 episode] Tokyo Ghoul S2 - #17 ûA - Rift (24:10) [HD1080, English, Japanese]
[s02e18 episode] Tokyo Ghoul S2 - #18 ûA - Thousand Paths (24:11) [HD1080, English, Japanese]
[s02e19 episode] Tokyo Ghoul S2 - #19 ûA - Permeation (24:11) [HD1080, English, Japanese]
[s02e20 episode] Tokyo Ghoul S2 - #20 ûA - Old Nines (24:11) [HD1080, English, Japanese]
[s02e21 episode] Tokyo Ghoul S2 - #21 ûA - City In Waiting (24:11) [HD1080, English, Japanese]
[s02e22 episode] Tokyo Ghoul S2 - #22 ûA - Last Rain (24:11) [HD1080, English, Japanese]
[s02e23 episode] Tokyo Ghoul S2 - #23 ûA - Deluge of Flowers (24:09) [HD1080, English, Japanese]
[s02e24 episode] Tokyo Ghoul S2 - #24 ûA - Ken (24:11) [HD1080, English, Japanese]
Output filename: [Funimation] Tokyo Ghoul - 01 [720p]

Available audio tracks:
[#96310] English (selected)
[#95024] Japanese

> "streamlink" "hlsvariant://https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1351385/English/1351385_English_a3aae8fe-2854-e611-80c5-0017a4776c06.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMTMyZnVtaTZkaTF3YS5jbG91ZGZyb250Lm5ldC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDkzNTI4MzcxfX19XX0_&Signature=Cj2rz-ztpeaKm6cv4rXyOiqJzVwagkUQI17zQd1Tv88srjI0RL81Jl2wwvBhJsqT3JsoFb~zrXh66lEo3j7sEN3hHu8~i0s2ufilsx8o-7UL~I7PG6fl5va~MzJmLR-a7NS5mPWB-iUQBMquI7KAEwlB-Yikqe7s~q~q26qD8p1tiLxPuId7FaFN~FEL378KrEayzvV-w-hqypCXOTAx2eWhIe3VUT2ngCgr2pch2lgdrqgz2IdBG0PaFDp9u77BItwKrMEZzTbDIae2aW0geQvSxiWPKUYpAX4rLEDop9J8n8xyFnclRYowQ9R~pK2t-wCo10YFLj7IPoupT8naTA__&Key-Pair-Id=APKAIHNXECY27H4O6NIA" 720p --hls-segment-attempts 10 --hls-segment-threads 10 --hls-segment-timeout 60 -o "[Funimation] Tokyo Ghoul - 01 [720p].ts"

[Streamlink for Windows v0.5.0 - Git df8966b]
Traceback (most recent call last):
  File "D:\funimation-downloader-nx-master\bin\streamlink\build\Streamlink\Streamlink.py", line 4, in <module>
    from streamlink_cli.main import main
  File "D:\funimation-downloader-nx-master\bin\streamlink\build\Streamlink\streamlink_cli\main.py",line 14, in <module>
    from streamlink import (Streamlink, StreamError, PluginError,
ImportError: No module named 'streamlink'
[End of Streamlink for Windows]
child_process.js:524
    throw err;
    ^

Error: Command failed: "D:\funimation-downloader-nx-master\bin\streamlink\build\streamlink" "hlsvariant://https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1351385/English/1351385_English_a3aae8fe-2854-e611-80c5-0017a4776c06.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMTMyZn
VtaTZkaTF3YS5jbG91ZGZyb250Lm5ldC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDkzNTI4MzcxfX19XX0_&Signature=Cj2rz-ztpeaKm6cv4rXyOiqJzVwagkUQI17zQd1Tv88srjI0RL81Jl2wwvBhJsqT3JsoFb~zrXh66lEo3j7sEN3hHu8~i0s2ufilsx8o-7UL~I7PG6fl5va~MzJmLR-a7NS5mPWB-iUQBMquI7KAEwlB-Yikqe7s~q~q26qD8p1tiLxPuId7FaFN~FEL378KrEayzvV-w-hqypCXOTAx2eWhIe3VUT2ngCgr2pch2lgdrqgz2IdBG0PaFDp9u77BItwKrMEZzTbDIae2aW0geQvSxiWPKUYpAX4rLEDop9J8n8xyFnclRYowQ9R~pK2t-wCo10YFLj7IPoupT8naTA__&Key-Pair-Id=APKAIHNXECY27H4O6NIA" 720p --hls-segment-attempts 10 --hls-segment-threads 10 --hls-segment-timeout 60 -o "[Funimation] Tokyo Ghoul - 01 [720p].ts"
    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at Object.exec (D:\funimation-downloader-nx-master\scripts\node_modules\sei-helper\sei-helper.js:126:28)
    at downloadStream (D:\funimation-downloader-nx-master\scripts\funidl.js:433:7)
    at parseStream (D:\funimation-downloader-nx-master\scripts\funidl.js:420:4)
    at Request.request.get [as _callback] (D:\funimation-downloader-nx-master\scripts\funidl.js:402:4)
    at Request.self.callback (D:\funimation-downloader-nx-master\scripts\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (D:\funimation-downloader-nx-master\scripts\node_modules\request\request.js:1171:10)
Press any key to continue . . .

D:\funimation-downloader-nx-master>
```
WIll continue to work on it in between Cybersecurity homework sessions. :)

**Comment by seiya-git** [comment]
You need move folders too.
![default](https://cloud.githubusercontent.com/assets/7394323/25566410/b7c681c2-2de0-11e7-8f38-f20b67f24edc.png)

**Comment by leptoid** [comment]
I should have mentioned I relocated it all.  Sorry about that.
![streamlink](https://cloud.githubusercontent.com/assets/18079714/25568027/c3946788-2dbf-11e7-8cca-02d05c0fa74d.JPG)

**Comment by leptoid** [comment]
So, I deleted Streamlink again, recompiled it again, copied it to the folder again (a lot of agains are happening here), and now it is working!  IT IS WORKING! 
:D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D :D 

Ok, that might have been a little bit over celebratory, but what can I say?  Oh yeah... Thanks!

**Comment by CrazySD93** [comment]
Launching from powershell, Windows 10.

```
PS F:\funimation-downloader-nx-master> ./funi -s 369617 --sel S001

=== Funimation Downloader NX 2.5.0 ===

[#369617] Seven Mortal Sins (2017)
[0001] Seven Mortal Sins - #01 The Proud Fallen Angel (23:36) [HD1080, English]
[0002] Seven Mortal Sins - #02 Driven Wild by Envy (23:36) [HD1080, English]
[0003] Seven Mortal Sins - #03 Beach of Lust (23:36) [HD1080, English]
[0004] Seven Mortal Sins - #04 The Town of Fog Where Greed Brews (23:36) [HD1080, English]
[S001] Seven Mortal Sins - #04.5 This is Indeed the Work of Demons… (23:36) [HD1080, English] (selected)
[0005] Seven Mortal Sins - #05 The Languid Diva (23:36) [HD1080, English]
[0006] Seven Mortal Sins - #06 Sloth Online (23:36) [HD1080, English]
[0007] Seven Mortal Sins - #07 Guiltless Gluttony (23:36) [HD1080, English]
[0008] Seven Mortal Sins - #08 Unleashed Wrath (23:36) [HD1080, English]
[0009] Seven Mortal Sins - #09 Ye Abandon All Hope (23:36) [HD1080, English]
[0010] Seven Mortal Sins - #10 Love Your Enemies and Pray for Those Who Persecute You (23:36) [HD1080, English]
[0011] Seven Mortal Sins - #11 Ask, and It Shall Be Given to You (23:36) [HD1080, English]
[0012] Seven Mortal Sins - #12 God's In His Heaven, All's Right With the World (23:36) [HD1080, English]

[INFO] Output filename: [Funimation] Seven Mortal Sins - 04.5 [1080p]

[INFO] Available audio tracks:
[#384021] English (selected)
Error:
Status: 404
    at Request.request [as _callback] (F:\funimation-downloader-nx-master\scripts\funidl.js:459:19)
    at Request.self.callback (F:\funimation-downloader-nx-master\scripts\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (F:\funimation-downloader-nx-master\scripts\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (F:\funimation-downloader-nx-master\scripts\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20) '\n'
Press any key to continue . . .
```

if it has something to do with setting the boolean settings on the funidl.js; I can't seem to figure out how to properly set them to have an affect, .boolean('h')
