### ISSUE TITLE
Consecutive Instances Under Same Cmd Prompt Fail

### ISSUE THREAD

**Issue by leptoid** [seiya-dev/funimation-downloader-nx#4]
To start, the program is functioning great, however, if it successfully pulls an episode, it seems to not want to pull a second one under the same command prompt.  Running an elevated (Administrative) command prompt does not change this behavior.  Was not tested in Powershell.

As of this moment, the only solution appears to be closing the current prompt and opening a new one... then it works for a single episode again. :)
```
[avc-h264] Possible Variable Frame Rate: VUI "fixed_frame_rate_flag" absent.
AVC-H264 import - frame size 1280 x 720 at 23.976 FPS
AVC Import results: 34672 samples (106387 NALUs) - Slices: 890 I 14392 P 19390 B - 33239 SEI - 790 I
DR
Stream uses forward prediction - stream CTS offset: 2 frames
AAC ADTS import  - sample rate 48000 - MPEG-4 audio - 2 channels
Saving [Funimation] Tokyo Ghoul - 02 [720p].mp4: 0.500 secs Interleaving

Done!

Press any key to continue . . .

D:\funimation-downloader-nx-master>funi -s 37172 --sel 3

=== Funimation Downloader NX 2.2.5 ===

[s01e01 episode] Tokyo Ghoul - #1 Tragedy (26:08) [HD1080, English, Japanese]
[s01e02 episode] Tokyo Ghoul - #2 Incubation (24:06) [HD1080, Japanese, English]
[s01e03 episode] Tokyo Ghoul - #3 Dove (24:06) [HD1080, English, Japanese] (selected)
[s01e04 episode] Tokyo Ghoul - #4 Supper (24:06) [HD1080, English, Japanese]
[s01e05 episode] Tokyo Ghoul - #5 Scars (24:11) [HD1080, English, Japanese]
[s01e06 episode] Tokyo Ghoul - #6 Cloudburst (24:06) [HD1080, Japanese, English]
[s01e07 episode] Tokyo Ghoul - #7 Captivity (24:12) [HD1080, English, Japanese]
[s01e08 episode] Tokyo Ghoul - #8 Circular (24:11) [HD1080, English, Japanese]
[s01e09 episode] Tokyo Ghoul - #9 Birdcage (24:11) [HD1080, English, Japanese]
[s01e10 episode] Tokyo Ghoul - #10 Aogiri (24:11) [HD1080, English, Japanese]
[s01e11 episode] Tokyo Ghoul - #11 High Spirits (24:11) [HD1080, English, Japanese]
[s01e12 episode] Tokyo Ghoul - #12 Ghoul (24:11) [HD1080, English, Japanese]
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: write EIO
    at exports._errnoException (util.js:1050:11)
    at WriteStream.Socket._writeGeneric (net.js:724:26)
    at WriteStream.Socket._write (net.js:743:8)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at WriteStream.Writable.write (_stream_writable.js:241:11)
    at WriteStream.Socket.write (net.js:670:40)
    at Console.log (console.js:43:16)
    at parseEpsData (D:\funimation-downloader-nx-master\scripts\funidl.js:304:11)
    at Request.request.get [as _callback] (D:\funimation-downloader-nx-master\scripts\funidl.js:267:
4)
Press any key to continue . . .

D:\funimation-downloader-nx-master>

```

**Comment by leptoid** [comment]
Apparently this is already being worked.  In newest version with funi.js dated 29-Apr-2017 the error has changed to the following:
```
=== Funimation Downloader NX 2.3.1 ===

[#37172] Tokyo Ghoul (2014)
[0001] Tokyo Ghoul - #01 Tragedy (26:08) [HD1080, English, Japanese]
[0002] Tokyo Ghoul - #02 Incubation (24:06) [HD1080, Japanese, English]
[0003] Tokyo Ghoul - #03 Dove (24:06) [HD1080, English, Japanese]
[0004] Tokyo Ghoul - #04 Supper (24:06) [HD1080, English, Japanese]
[0005] Tokyo Ghoul - #05 Scars (24:11) [HD1080, English, Japanese] (selected)
[0006] Tokyo Ghoul - #06 Cloudburst (24:06) [HD1080, Japanese, English]
[0007] Tokyo Ghoul - #07 Captivity (24:12) [HD1080, English, Japanese]
[0008] Tokyo Ghoul - #08 Circular (24:11) [HD1080, English, Japanese]
[0009] Tokyo Ghoul - #09 Birdcage (24:11) [HD1080, English, Japanese]
[0010] Tokyo Ghoul - #10 Aogiri (24:11) [HD1080, English, Japanese]
[0011] Tokyo Ghoul - #11 High Spirits (24:11) [HD1080, English, Japanese]
[0012] Tokyo Ghoul - #12 Ghoul (24:11) [HD1080, English, Japanese]
(node:3192) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: write EIO
(node:3192) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Press any key to continue . . .
```

**Comment by leptoid** [comment]
I am testing this method for batching:
Step 1:  Figure out show # and episode numbers
Step 2:  Create txt file with the following info:
```
start /wait cmd.exe /c D:\funimation-downloader-nx-master\funi.bat -s ##### --sel #
start /wait cmd.exe /c D:\funimation-downloader-nx-master\funi.bat -s ##### --sel #
start /wait cmd.exe /c D:\funimation-downloader-nx-master\funi.bat -s ##### --sel #
start /wait cmd.exe /c D:\funimation-downloader-nx-master\funi.bat -s ##### --sel #
start /wait cmd.exe /c D:\funimation-downloader-nx-master\funi.bat -s ##### --sel #
start /wait cmd.exe /c D:\funimation-downloader-nx-master\funi.bat -s ##### --sel #
start /wait cmd.exe /c D:\funimation-downloader-nx-master\funi.bat -s ##### --sel #
start /wait cmd.exe /c D:\funimation-downloader-nx-master\funi.bat -s ##### --sel #
start /wait cmd.exe /c D:\funimation-downloader-nx-master\funi.bat -s ##### --sel #
start /wait cmd.exe /c D:\funimation-downloader-nx-master\funi.bat -s ##### --sel #
```
##### = Show #
# = Episode number

Step 3:  Rename the file extension to .bat
Step 4:  Run the file.

Turns out this works however, main script will require modification to take out the pause after the final step otherwise it gets stuck waiting.

**Comment by seiya-git** [comment]
This bug has already been discussed in #1.
Replace funi.bat with [this file](https://github.com/seiya-dev/funimation-downloader-nx/blob/master/funi.bat).

**Comment by leptoid** [comment]
Hmm... I had done that.  It just didn't want to work last night.  Works flawlessly today though.  Problem solved (apparently before I even posted it). :)
