### ISSUE TITLE
UnhandledPromiseRejectionWarning with invalid token?

### ISSUE THREAD

**Issue by shinji257** [seiya-dev/funimation-downloader-nx#41]
** Main info: **

Script version: 4.1.0
Show ID: N/A
Episode ID: N/A

** Additional Info: **
If the script has a token but it is invalid it seems that it might not be getting handled properly.

```
shinji@ubuntu_1604:~/funimation-downloader-nx> node funi.js -s 25916

=== Funimation Downloader NX 4.1.0 ===

[ERROR] Show not found

(node:19683) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at getShow (/home/shinji/funimation-downloader-nx/funi.js:215:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19683) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I was able to resolve this by logging in again and getting a new token.

**Comment by seiya-git** [comment]
Thanks! I look at it when migrate to `got`.

**Comment by seiya-git** [comment]
try new version
