### ISSUE TITLE
no cloudfront.net server as main

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [seiya-dev/funimation-downloader-nx#42]
@seiya-git

** Main info: **

Script version: 4.2.1
Show ID: 848368
Episode ID: 05

`=== Funimation Downloader NX 4.2.1 ===

[#848368] Wise Man's Grandchild (2019)
[0001] Wise Man's Grandchild - #01 A Babe in the Woods Goes to the Capital (23:40) [HD1080, Japanese, English]
[0002] Wise Man's Grandchild - #02 The Unconventional New Student (23:40) [HD1080, English, Japanese]
[0003] Wise Man's Grandchild - #03 An Emergency Arises! (23:40) [HD1080, English, Japanese]
[0004] Wise Man's Grandchild - #04 The Name of the Instigator (23:40) [HD1080, English, Japanese]
[0005] Wise Man's Grandchild - #05 A Pioneering New Hero (23:39) [HD1080, Japanese, English] (selected)

[INFO] Selected Episodes: 0005

[INFO] Wise Man's Grandchild - S1E05 - A Pioneering New Hero
[INFO] Available streams (Non-Encrypted):
[#848419] Japanese [Simulcast] 
[#848415] English [Simulcast] (selected)
(node:78328) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
    at downloadStreams (/Users/ovidijus/Apps/Animie/funimation-downloader-nx/funi.js:512:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:78328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:78328) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

=== Funimation Downloader NX 4.2.1 ===

[#800830] The Rising of the Shield Hero (2019)
[0001] The Rising of the Shield Hero - #01 The Shield Hero (47:20) [HD1080, Japanese, English]
[0002] The Rising of the Shield Hero - #02 The Slave Girl (23:39) [HD1080, English, Japanese] (selected)
[0003] The Rising of the Shield Hero - #03 Wave of Catastrophe (23:40) [HD1080, English, Japanese]
[0004] The Rising of the Shield Hero - #04 Lullaby at Dawn (23:40) [HD1080, English, Japanese]
[0005] The Rising of the Shield Hero - #05 Filo (23:40) [HD1080, English, Japanese]
[0006] The Rising of the Shield Hero - #06 A New Comrade (23:40) [HD1080, English, Japanese]
[0007] The Rising of the Shield Hero - #07 The Savior of the Heavenly Fowl (23:39) [HD1080, English, Japanese]
[0008] The Rising of the Shield Hero - #08 Curse Shield (23:40) [HD1080, English, Japanese]
[0009] The Rising of the Shield Hero - #09 Melty (23:39) [HD1080, English, Japanese]
[0010] The Rising of the Shield Hero - #10 In the Midst of Turmoil (23:39) [HD1080, English, Japanese]
[0011] The Rising of the Shield Hero - #11 Catastrophe Returns (23:40) [HD1080, English, Japanese]
[0012] The Rising of the Shield Hero - #12 The Raven Invader (23:40) [HD1080, English, Japanese]
[0013] The Rising of the Shield Hero - #13 The Devil of the Shield (23:40) [HD1080, English, Japanese]
[0014] The Rising of the Shield Hero - #14 Everlasting Memory (23:40) [HD1080, English, Japanese]
[0015] The Rising of the Shield Hero - #15 Raphtalia (23:40) [HD1080, English, Japanese]
[0016] The Rising of the Shield Hero - #16 Filolial Queen (23:40) [HD1080, English, Japanese]
[0017] The Rising of the Shield Hero - #17 A Promise Made (23:40) [HD1080, English, Japanese]
[0018] The Rising of the Shield Hero - #18 A Conspiracy Linked (23:40) [HD1080, English, Japanese]

[INFO] Selected Episodes: 0002

[INFO] The Rising of the Shield Hero - S1E02 - The Slave Girl
[INFO] Available streams (Non-Encrypted):
[#859204] Japanese [Simulcast] 
[#861157] English [Simulcast] (selected)
(node:78713) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
    at downloadStreams (/Users/ovidijus/Apps/Animie/funimation-downloader-nx/funi.js:512:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:78713) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:78713) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Running NPM Ver: 6.4.1
node: stable 12.1.0

**Comment by XxUnkn0wnxX** [comment]
i think this might be a region thing. i tried several VPN spots, AUS - Sydney, Perth | USA - Los Angeles, Denvar & all kept giving me error. when i connected to USA - Phoenix

it managed to start but still failed:

`[INFO] Wise Man's Grandchild - S1E05 - A Pioneering New Hero
[INFO] Available streams (Non-Encrypted):
[#848419] Japanese [Simulcast] 
[#848415] English [Simulcast] (selected)
[INFO] Selected layer: 10
	Available qualities:
		1: 234p (526KiB/s)
		10: 1080p (9559KiB/s)
		2: 270p (757KiB/s)
		3: 360p (987KiB/s)
		4: 360p (1713KiB/s)
		5: 540p (2407KiB/s)
		6: 720p (3086KiB/s)
		7: 720p (4418KiB/s)
		8: 810p (6085KiB/s)
		9: 1080p (7694KiB/s)
[INFO] Selected server: 1 / Total servers available: 3
[INFO] Stream URL: https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1961472/English/1961472_English_c0ed357b-5c5a-e911-8175-020165574d09_Layer10.m3u8
[INFO] Output filename: [Funimation] Wise Man's Grandchild - 05 [1080p]
[INFO] Starting downloading ts...
[INFO] Saving stream to «[Funimation] Wise Man's Grandchild - 05 [1080p].ts»...
[INFO] 10 parts of 179 downloaded [6%] (3m44s)
[INFO] 20 parts of 179 downloaded [11%] (4m24s)
[INFO] 30 parts of 179 downloaded [17%] (3m44s)
[INFO] 40 parts of 179 downloaded [22%] (3m26s)
[ERROR] Part 50 download error:
	error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
[ERROR] Part 50 download error:
	error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
[ERROR] Part 50 download error:
	error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
[ERROR] Part 50 download error:
	error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
[ERROR] Part 50 download error:
	error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
[ERROR] Part 50 download error:
	error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
[ERROR] Part 50 download error:
	error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
[ERROR] Part 50 download error:
	error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
[ERROR] undefined`

**Comment by XxUnkn0wnxX** [comment]
after some further testing it seems to be a server issue for some reason server 1 https://d132fumi6di1wa.cloudfront.net is failing with the script..
