### ISSUE TITLE
URLSearchParams is not defined

### ISSUE THREAD

**Issue by nolan1989** [seiya-dev/funimation-downloader-nx#44]
** Main info: **
I receive an error while search for shows with the new script. I've made sure everything is the correct version(uninstalled everything and started from scratch even).

Script version: 4.3.2
OS: Windows 10

** Additional Info: **

(node:5424) UnhandledPromiseRejectionWarning: ReferenceError: URLSearchParams is not defined
    at getData (E:\funimationDownloader\funi.js:678:33)
    at searchShow (E:\funimationDownloader\funi.js:208:28)
    at Object.<anonymous> (E:\funimationDownloader\funi.js:171:5)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
(node:5424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:5424) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by seiya-git** [comment]
which node version you use?

**Comment by nolan1989** [comment]
9.4

**Comment by seiya-git** [comment]
Try to update to 12.2.0

**Comment by nolan1989** [comment]
That worked. Thanks
