### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by clienthax** [seiya-dev/funimation-downloader-nx#6]
Downloaded master, went into scripts folder, did npm i, that succeeded.

When attempting to run the batch file 
```
C:\Scripts\funimation-downloader-nx-master>funi
C:\Scripts\funimation-downloader-nx-master\scripts\funidl.js:131
async function auth(){
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
Press any key to continue . . .```


```
C:\Scripts\funimation-downloader-nx-master>node -v
v6.10.3

C:\Scripts\funimation-downloader-nx-master>npm -v
3.10.10
```

**Comment by clienthax** [comment]
Solved on my own, needs the current version of node, instead of the recommended
